### ISSUE TITLE
Create an GitHub action for CI and deployment.

### ISSUE THREAD

**Issue by razonyang** [hugomods/docker#49]

**Comment by razonyang** [comment]
GitHub Actions already support this, I didn't test the following code, there maybe typo or mistake.

```yaml
      - name: Build
        uses: docker://hugomods/hugo
        with:
          args: |
            sh -c "hugo --minify"
```
